### ISSUE TITLE
Add contributors to this resource

### ISSUE THREAD

**Issue by ekuw** [JGIBristol/ask-jgi-handbook#9]
Issue to request addition of contributors using [all-contributors](https://allcontributors.org/) bot

**Comment by ekuw** [comment]
@all-contributors please add @NatalieZelenka for ideas

**Comment by ekuw** [comment]
@all-contributors please add @ekuw for projectManagement and maintenance

**Comment by ekuw** [comment]
@all-contributors please add @Jean-Golding-Institute for financial and fundingFinding

**Comment by jatonline** [comment]
@all-contributors
please add @l-gorman for Documentation; Maintenance; Ideas, Planning, & Feedback.
please add @l-gorman for Documentation; Maintenance; Ideas, Planning, & Feedback.
please add @l-gorman for Documentation; Maintenance; Ideas, Planning, & Feedback.
please add @l-gorman for Documentation; Maintenance; Ideas, Planning, & Feedback.

**Comment by jatonline** [comment]
@all-contributors
please add @lippirk for Documentation; Maintenance; Ideas, Planning, & Feedback.
please add @mgchandler for Documentation; Maintenance; Ideas, Planning, & Feedback.
please add @mvab for Documentation; Maintenance; Ideas, Planning, & Feedback.
please add @vairylein for Documentation; Maintenance; Ideas, Planning, & Feedback.
please add @xintu59 for Documentation; Maintenance; Ideas, Planning, & Feedback; Project Management.
please add @RichardP1234 for Documentation; Maintenance; Ideas, Planning, & Feedback; Project Management.
please add @WillGChapman for Ideas, Planning, & Feedback.

**Comment by jatonline** [comment]
@all-contributors
please add @mgchandler for Documentation; Maintenance; Ideas, Planning, & Feedback.

**Comment by jatonline** [comment]
@all-contributors please add @xintu59 for Documentation; Maintenance; Ideas, Planning, & Feedback; Project Management.
